In [1]:
import pandas as pd
import os
import string
import re
import nltk

In [3]:
job_dataset = pd.read_csv(r"/home/dell/Desktop/Skill_gap/job_descriptions.csv")
# job_dataset.head()

In [2]:
missing_values = job_dataset.isnull().sum()
# display("Missing Values:\n", missing_values)

NameError: name 'job_dataset' is not defined

In [ ]:
job_dataset = job_dataset.dropna()
# display(job_dataset)

In [ ]:
# Example: Convert 'Job Posting Date' to datetime format
job_dataset['Job Posting Date'] = pd.to_datetime(job_dataset['Job Posting Date'])

In [ ]:
# removed latitude and longitude columns,since we have country
job_dataset = job_dataset.drop(['latitude', 'longitude', 'Contact'], axis=1)
# display(job_dataset)

In [ ]:
# covert all data to lower case
job_dataset = job_dataset.applymap(lambda x: x.lower() if isinstance(x, str) else x)
# display(job_dataset)

In [9]:
def remove_punctuation_from_cell(cell):
    translator = str.maketrans("", "", string.punctuation)
    return str(cell).translate(translator)

for column in job_dataset.columns:
    if  job_dataset[column].dtype == 'object': # Check if the column contains text
        job_dataset[column] = job_dataset[column].apply(remove_punctuation_from_cell)
        
#         display(job_dataset)

In [10]:
  # adding a standardized format with a hyphen in Salary Range Column
def clean_salary_range(salary_range):
    min_salary = salary_range[:2]
    max_salary = salary_range[3:]
    
    #adding a standardized format with a hyphen
    standardized_salary_range = f"{min_salary}-{max_salary}"
    
    return standardized_salary_range

job_dataset['Salary Range'] = job_dataset['Salary Range'].apply(clean_salary_range)
# display(job_dataset)

In [14]:
# putting spaces b2n words in Compony profile column
def add_spaces(text):
    clean_text = re.sub(r'(sector|industry|other_keyword)', r'\1 ', text)
    
    return clean_text

job_dataset['Company Profile'] = job_dataset['Company Profile'].apply(add_spaces)

def add_space_before_industry(text):
    return text.replace('industry', ' industry')

job_dataset['Company Profile'] = job_dataset['Company Profile'].apply(add_space_before_industry)
# display(job_dataset)

In [12]:
# Have created a version of my dataset, of the cleaned data
job_dataset.to_csv('cleaned_data.csv', index=False)

In [ ]:
cleaned_dataset = pd.read_csv('/home/dell/Desktop/Projects/Skill_gap/cleaned_data.csv')
# cleaned_dataset.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 years,mtech,59-99k,douglas,isle of man,intern,26801,2022-04-24,female,brandon cunningham,digital marketing specialist,social media manager,snagajob,social media managers oversee an organizations...,flexible spending accounts fsas relocation ass...,social media platforms eg facebook twitter ins...,manage and grow social media accounts create e...,icahn enterprises,sector diversified industry diversified financ...
1,398454096642776,2 to 12 years,bca,56-116k,ashgabat,turkmenistan,intern,100340,2022-12-19,female,francisco larsen,web developer,frontend web developer,idealist,frontend web developers design and implement u...,health insurance retirement plans paid time of...,html css javascript frontend frameworks eg rea...,design and code user interfaces for websites e...,pnc financial services group,sector financial services industry commercial ...
2,481640072963533,0 to 12 years,phd,61-104k,macao,macao sar china,temporary,84525,2022-09-14,male,gary gibson,operations manager,quality control manager,jobs2careers,quality control managers establish and enforce...,legal assistance bonuses and incentive program...,quality control processes and methodologies st...,establish and enforce quality control standard...,united services automobile assn,sector insurance industry insurance property a...
3,688192671473044,4 to 11 years,phd,65-91k,portonovo,benin,fulltime,129896,2023-02-25,female,joy lucero,network engineer,wireless network engineer,flexjobs,wireless network engineers design implement an...,transportation benefits professional developme...,wireless network design and architecture wifi ...,design configure and optimize wireless network...,hess,sector energy industry mining crudeoil product...
4,117057806156508,1 to 12 years,mba,64-87k,santiago,chile,intern,53944,2022-10-11,female,julie johnson,event manager,conference manager,jobs2careers,a conference manager coordinates and manages c...,flexible spending accounts fsas relocation ass...,event planning conference logistics budget man...,specialize in conference and convention planni...,cairn energy,sector energy industry energy oil gas explor...

In [ ]:
total_rows = len(cleaned_dataset)
quater_rows = total_rows // 3

working_data = cleaned_dataset.iloc[:quater_rows, :]
second_quater = cleaned_dataset.iloc[:quater_rows, :]
third_quater = cleaned_dataset.iloc[:quater_rows, :]

# show all the rows
# display(working_data)

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 years,mtech,59-99k,douglas,isle of man,intern,26801,2022-04-24,female,brandon cunningham,digital marketing specialist,social media manager,snagajob,social media managers oversee an organizations...,flexible spending accounts fsas relocation ass...,social media platforms eg facebook twitter ins...,manage and grow social media accounts create e...,icahn enterprises,sector diversified industry diversified financ...
1,398454096642776,2 to 12 years,bca,56-116k,ashgabat,turkmenistan,intern,100340,2022-12-19,female,francisco larsen,web developer,frontend web developer,idealist,frontend web developers design and implement u...,health insurance retirement plans paid time of...,html css javascript frontend frameworks eg rea...,design and code user interfaces for websites e...,pnc financial services group,sector financial services industry commercial ...
2,481640072963533,0 to 12 years,phd,61-104k,macao,macao sar china,temporary,84525,2022-09-14,male,gary gibson,operations manager,quality control manager,jobs2careers,quality control managers establish and enforce...,legal assistance bonuses and incentive program...,quality control processes and methodologies st...,establish and enforce quality control standard...,united services automobile assn,sector insurance industry insurance property a...
3,688192671473044,4 to 11 years,phd,65-91k,portonovo,benin,fulltime,129896,2023-02-25,female,joy lucero,network engineer,wireless network engineer,flexjobs,wireless network engineers design implement an...,transportation benefits professional developme...,wireless network design and architecture wifi ...,design configure and optimize wireless network...,hess,sector energy industry mining crudeoil product...
4,117057806156508,1 to 12 years,mba,64-87k,santiago,chile,intern,53944,2022-10-11,female,julie johnson,event manager,conference manager,jobs2careers,a conference manager coordinates and manages c...,flexible spending accounts fsas relocation ass...,event planning conference logistics budget man...,specialize in conference and convention planni...,cairn energy,sector energy industry energy oil gas explor...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536815,508728644148006,0 to 14 years,bba,59-106k,sofia,bulgaria,fulltime,30750,2023-06-14,male,perry butler,ux researcher,user researcher,indeed,conduct user research to understand customer n...,flexible spending accounts fsas relocation ass...,user research methods usability testing data a...,conduct user research to understand user behav...,stonex group,sector financial services industry diversified...
536816,505706031713498,0 to 13 years,btech,62-126k,riga,latvia,fulltime,68266,2022-10-28,both,rebecca clark,business analyst,data business analyst,glassdoor,data business analysts focus on datarelated pr...,casual dress code social and recreational acti...,data analysis data modeling data visualization...,focus on data analysis data modeling and data ...,whirlpool,sector manufacturing industry electronics elec...
536817,2043878419632350,0 to 14 years,ba,63-107k,lomã©,togo,intern,59180,2021-11-14,male,gary hunt,sales representative,outside sales representative,indeed,outside sales representatives meet with potent...,tuition reimbursement stock options or equity ...,sales prospecting and networking facetoface sa...,meet potential clients in person attend indust...,western digital,sector technology industry computers office eq...
536818,2865822743605959,2 to 15 years,bcom,63-85k,ottawa,canada,parttime,110969,2022-09-17,female,richard flores,uxui designer,user interface designer,usajobs,user interface designers focus on the visual a...,transportation benefits professional developme...,ui design principles and best practices graphi...,create visually appealing user interfaces ui t...,ford motor,sector automotive industry motor vehicles par...
536819,953081681199738,2 to 9 years,ba,58-111k,papeete,french polynesia,temporary,14271,2021-10-18,male,michael cortez,interior designer,hospitality interior designer,indeed,a hospitality interior designer specializes in...,flexible spending accounts fsas relocation ass...,hospitality interior design hotel and restaura...,specialize in designing interiors for hotels r...,sun pharmaceutical industries,sector pharmaceuticals industry pharmaceutical...

In [6]:
from nltk.tokenize import word_tokenize

def tokenize_text(text):
    tokens = word_tokenize(text)
    return tokens
working_data.loc[:, 'Qualifications'] = working_data['Qualifications'].apply(word_tokenize)
# display(working_data)

In [7]:
working_data.loc[:, 'Job Title'] = working_data['Job Title'].apply(tokenize_text)

In [8]:
working_data.loc[:, 'Role'] = working_data['Role'].apply(tokenize_text)

In [9]:
working_data.loc[:, 'Job Portal'] = working_data['Job Portal'].apply(word_tokenize)

In [10]:
working_data.loc[:, 'Job Description'] = working_data['Job Description'].apply(tokenize_text)

In [11]:
working_data.loc[:, 'Benefits'] = working_data['Benefits'].apply(tokenize_text)

In [12]:
working_data.loc[:, 'skills'] = working_data['skills'].apply(word_tokenize)

In [13]:
working_data.loc[:, 'Responsibilities'] = working_data['Responsibilities'].apply(word_tokenize)

In [14]:
working_data.loc[:, 'Preference'] = working_data['Preference'].apply(word_tokenize)

In [15]:
working_data.loc[:, 'Company'] = working_data['Company'].apply(word_tokenize)

In [16]:
working_data.loc[:, 'Company Profile'] = working_data['Company Profile'].apply(word_tokenize)

In [17]:
working_data.to_csv('tokenized_cleaned_data.csv', index=False)

In [3]:
tokenized_data = pd.read_csv('/home/dell/Desktop/Projects/Skill_gap/tokenized_cleaned_data.csv')
# tokenized_data.head()

In [7]:
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Assuming 'text_column' is the name of the column containing the text data
text_column = 'skills'  # Replace 'your_column_name' with the actual column name

# Download NLTK stop words
stop_words = set(stopwords.words('english'))

# Function to remove stop words from a text
def remove_stopwords(text):
    words = word_tokenize(text)
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

# Apply the function to the specified column
tokenized_data[text_column] = tokenized_data[text_column].apply(remove_stopwords)

# Display the updated DataFrame
tokenized_data.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 years,['mtech'],59-99k,douglas,isle of man,intern,26801,2022-04-24,['female'],brandon cunningham,"['digital', 'marketing', 'specialist']","['social', 'media', 'manager']",['snagajob'],"['social', 'media', 'managers', 'oversee', 'an...","['flexible', 'spending', 'accounts', 'fsas', '...","[ 'social ' , 'media ' , 'platforms ' , 'eg ' ...","['manage', 'and', 'grow', 'social', 'media', '...","['icahn', 'enterprises']","['sector', 'diversified', 'industry', 'diversi..."
1,398454096642776,2 to 12 years,['bca'],56-116k,ashgabat,turkmenistan,intern,100340,2022-12-19,['female'],francisco larsen,"['web', 'developer']","['frontend', 'web', 'developer']",['idealist'],"['frontend', 'web', 'developers', 'design', 'a...","['health', 'insurance', 'retirement', 'plans',...","[ 'html ' , 'css ' , 'javascript ' , 'frontend...","['design', 'and', 'code', 'user', 'interfaces'...","['pnc', 'financial', 'services', 'group']","['sector', 'financial', 'services', 'industry'..."
2,481640072963533,0 to 12 years,['phd'],61-104k,macao,macao sar china,temporary,84525,2022-09-14,['male'],gary gibson,"['operations', 'manager']","['quality', 'control', 'manager']",['jobs2careers'],"['quality', 'control', 'managers', 'establish'...","['legal', 'assistance', 'bonuses', 'and', 'inc...","[ 'quality ' , 'control ' , 'processes ' , 'an...","['establish', 'and', 'enforce', 'quality', 'co...","['united', 'services', 'automobile', 'assn']","['sector', 'insurance', 'industry', 'insurance..."
3,688192671473044,4 to 11 years,['phd'],65-91k,portonovo,benin,fulltime,129896,2023-02-25,['female'],joy lucero,"['network', 'engineer']","['wireless', 'network', 'engineer']",['flexjobs'],"['wireless', 'network', 'engineers', 'design',...","['transportation', 'benefits', 'professional',...","[ 'wireless ' , 'network ' , 'design ' , 'and ...","['design', 'configure', 'and', 'optimize', 'wi...",['hess'],"['sector', 'energy', 'industry', 'mining', 'cr..."
4,117057806156508,1 to 12 years,['mba'],64-87k,santiago,chile,intern,53944,2022-10-11,['female'],julie johnson,"['event', 'manager']","['conference', 'manager']",['jobs2careers'],"['a', 'conference', 'manager', 'coordinates', ...","['flexible', 'spending', 'accounts', 'fsas', '...","[ 'event ' , 'planning ' , 'conference ' , 'lo...","['specialize', 'in', 'conference', 'and', 'con...","['cairn', 'energy']","['sector', 'energy', 'industry', 'energy', 'oi..."

In [5]:
tokenized_data['Job Description'] = tokenized_data['Job Description'].apply(remove_stopwords)
# tokenized_data.head()

NameError: name 'remove_stopwords' is not defined

In [10]:
tokenized_data['Benefits'] = tokenized_data['Benefits'].apply(remove_stopwords)
tokenized_data.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 years,['mtech'],59-99k,douglas,isle of man,intern,26801,2022-04-24,['female'],brandon cunningham,"['digital', 'marketing', 'specialist']","['social', 'media', 'manager']",['snagajob'],"[ 'social ' , 'media ' , 'managers ' , 'overse...","[ 'flexible ' , 'spending ' , 'accounts ' , 'f...","['social', 'media', 'platforms', 'eg', 'facebo...","['manage', 'and', 'grow', 'social', 'media', '...","['icahn', 'enterprises']","['sector', 'diversified', 'industry', 'diversi..."
1,398454096642776,2 to 12 years,['bca'],56-116k,ashgabat,turkmenistan,intern,100340,2022-12-19,['female'],francisco larsen,"['web', 'developer']","['frontend', 'web', 'developer']",['idealist'],"[ 'frontend ' , 'web ' , 'developers ' , 'desi...","[ 'health ' , 'insurance ' , 'retirement ' , '...","['html', 'css', 'javascript', 'frontend', 'fra...","['design', 'and', 'code', 'user', 'interfaces'...","['pnc', 'financial', 'services', 'group']","['sector', 'financial', 'services', 'industry'..."
2,481640072963533,0 to 12 years,['phd'],61-104k,macao,macao sar china,temporary,84525,2022-09-14,['male'],gary gibson,"['operations', 'manager']","['quality', 'control', 'manager']",['jobs2careers'],"[ 'quality ' , 'control ' , 'managers ' , 'est...","[ 'legal ' , 'assistance ' , 'bonuses ' , 'and...","['quality', 'control', 'processes', 'and', 'me...","['establish', 'and', 'enforce', 'quality', 'co...","['united', 'services', 'automobile', 'assn']","['sector', 'insurance', 'industry', 'insurance..."
3,688192671473044,4 to 11 years,['phd'],65-91k,portonovo,benin,fulltime,129896,2023-02-25,['female'],joy lucero,"['network', 'engineer']","['wireless', 'network', 'engineer']",['flexjobs'],"[ 'wireless ' , 'network ' , 'engineers ' , 'd...","[ 'transportation ' , 'benefits ' , 'professio...","['wireless', 'network', 'design', 'and', 'arch...","['design', 'configure', 'and', 'optimize', 'wi...",['hess'],"['sector', 'energy', 'industry', 'mining', 'cr..."
4,117057806156508,1 to 12 years,['mba'],64-87k,santiago,chile,intern,53944,2022-10-11,['female'],julie johnson,"['event', 'manager']","['conference', 'manager']",['jobs2careers'],"[ ' ' , 'conference ' , 'manager ' , 'coordina...","[ 'flexible ' , 'spending ' , 'accounts ' , 'f...","['event', 'planning', 'conference', 'logistics...","['specialize', 'in', 'conference', 'and', 'con...","['cairn', 'energy']","['sector', 'energy', 'industry', 'energy', 'oi..."

In [11]:
tokenized_data['Responsibilities'] = tokenized_data['Responsibilities'].apply(remove_stopwords)
tokenized_data.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 years,['mtech'],59-99k,douglas,isle of man,intern,26801,2022-04-24,['female'],brandon cunningham,"['digital', 'marketing', 'specialist']","['social', 'media', 'manager']",['snagajob'],"[ 'social ' , 'media ' , 'managers ' , 'overse...","[ 'flexible ' , 'spending ' , 'accounts ' , 'f...","['social', 'media', 'platforms', 'eg', 'facebo...","[ 'manage ' , 'and ' , 'grow ' , 'social ' , '...","['icahn', 'enterprises']","['sector', 'diversified', 'industry', 'diversi..."
1,398454096642776,2 to 12 years,['bca'],56-116k,ashgabat,turkmenistan,intern,100340,2022-12-19,['female'],francisco larsen,"['web', 'developer']","['frontend', 'web', 'developer']",['idealist'],"[ 'frontend ' , 'web ' , 'developers ' , 'desi...","[ 'health ' , 'insurance ' , 'retirement ' , '...","['html', 'css', 'javascript', 'frontend', 'fra...","[ 'design ' , 'and ' , 'code ' , 'user ' , 'in...","['pnc', 'financial', 'services', 'group']","['sector', 'financial', 'services', 'industry'..."
2,481640072963533,0 to 12 years,['phd'],61-104k,macao,macao sar china,temporary,84525,2022-09-14,['male'],gary gibson,"['operations', 'manager']","['quality', 'control', 'manager']",['jobs2careers'],"[ 'quality ' , 'control ' , 'managers ' , 'est...","[ 'legal ' , 'assistance ' , 'bonuses ' , 'and...","['quality', 'control', 'processes', 'and', 'me...","[ 'establish ' , 'and ' , 'enforce ' , 'qualit...","['united', 'services', 'automobile', 'assn']","['sector', 'insurance', 'industry', 'insurance..."
3,688192671473044,4 to 11 years,['phd'],65-91k,portonovo,benin,fulltime,129896,2023-02-25,['female'],joy lucero,"['network', 'engineer']","['wireless', 'network', 'engineer']",['flexjobs'],"[ 'wireless ' , 'network ' , 'engineers ' , 'd...","[ 'transportation ' , 'benefits ' , 'professio...","['wireless', 'network', 'design', 'and', 'arch...","[ 'design ' , 'configure ' , 'and ' , 'optimiz...",['hess'],"['sector', 'energy', 'industry', 'mining', 'cr..."
4,117057806156508,1 to 12 years,['mba'],64-87k,santiago,chile,intern,53944,2022-10-11,['female'],julie johnson,"['event', 'manager']","['conference', 'manager']",['jobs2careers'],"[ ' ' , 'conference ' , 'manager ' , 'coordina...","[ 'flexible ' , 'spending ' , 'accounts ' , 'f...","['event', 'planning', 'conference', 'logistics...","[ 'specialize ' , 'in ' , 'conference ' , 'and...","['cairn', 'energy']","['sector', 'energy', 'industry', 'energy', 'oi..."

In [12]:
tokenized_data['Company Profile'] = tokenized_data['Company Profile'].apply(remove_stopwords)
tokenized_data.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 years,['mtech'],59-99k,douglas,isle of man,intern,26801,2022-04-24,['female'],brandon cunningham,"['digital', 'marketing', 'specialist']","['social', 'media', 'manager']",['snagajob'],"[ 'social ' , 'media ' , 'managers ' , 'overse...","[ 'flexible ' , 'spending ' , 'accounts ' , 'f...","['social', 'media', 'platforms', 'eg', 'facebo...","[ 'manage ' , 'and ' , 'grow ' , 'social ' , '...","['icahn', 'enterprises']","[ 'sector ' , 'diversified ' , 'industry ' , '..."
1,398454096642776,2 to 12 years,['bca'],56-116k,ashgabat,turkmenistan,intern,100340,2022-12-19,['female'],francisco larsen,"['web', 'developer']","['frontend', 'web', 'developer']",['idealist'],"[ 'frontend ' , 'web ' , 'developers ' , 'desi...","[ 'health ' , 'insurance ' , 'retirement ' , '...","['html', 'css', 'javascript', 'frontend', 'fra...","[ 'design ' , 'and ' , 'code ' , 'user ' , 'in...","['pnc', 'financial', 'services', 'group']","[ 'sector ' , 'financial ' , 'services ' , 'in..."
2,481640072963533,0 to 12 years,['phd'],61-104k,macao,macao sar china,temporary,84525,2022-09-14,['male'],gary gibson,"['operations', 'manager']","['quality', 'control', 'manager']",['jobs2careers'],"[ 'quality ' , 'control ' , 'managers ' , 'est...","[ 'legal ' , 'assistance ' , 'bonuses ' , 'and...","['quality', 'control', 'processes', 'and', 'me...","[ 'establish ' , 'and ' , 'enforce ' , 'qualit...","['united', 'services', 'automobile', 'assn']","[ 'sector ' , 'insurance ' , 'industry ' , 'in..."
3,688192671473044,4 to 11 years,['phd'],65-91k,portonovo,benin,fulltime,129896,2023-02-25,['female'],joy lucero,"['network', 'engineer']","['wireless', 'network', 'engineer']",['flexjobs'],"[ 'wireless ' , 'network ' , 'engineers ' , 'd...","[ 'transportation ' , 'benefits ' , 'professio...","['wireless', 'network', 'design', 'and', 'arch...","[ 'design ' , 'configure ' , 'and ' , 'optimiz...",['hess'],"[ 'sector ' , 'energy ' , 'industry ' , 'minin..."
4,117057806156508,1 to 12 years,['mba'],64-87k,santiago,chile,intern,53944,2022-10-11,['female'],julie johnson,"['event', 'manager']","['conference', 'manager']",['jobs2careers'],"[ ' ' , 'conference ' , 'manager ' , 'coordina...","[ 'flexible ' , 'spending ' , 'accounts ' , 'f...","['event', 'planning', 'conference', 'logistics...","[ 'specialize ' , 'in ' , 'conference ' , 'and...","['cairn', 'energy']","[ 'sector ' , 'energy ' , 'industry ' , 'energ..."

In [13]:
tokenized_data.to_csv('stopwords_cleaned_data.csv', index=False)

In [4]:
import pandas as pd

clean_data = pd.read_csv('/home/dell/Desktop/Projects/Skill_gap/stopwords_cleaned_data.csv')
clean_data.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 years,['mtech'],59-99k,douglas,isle of man,intern,26801,2022-04-24,['female'],brandon cunningham,"['digital', 'marketing', 'specialist']","['social', 'media', 'manager']",['snagajob'],"[ 'social ' , 'media ' , 'managers ' , 'overse...","[ 'flexible ' , 'spending ' , 'accounts ' , 'f...","['social', 'media', 'platforms', 'eg', 'facebo...","[ 'manage ' , 'and ' , 'grow ' , 'social ' , '...","['icahn', 'enterprises']","[ 'sector ' , 'diversified ' , 'industry ' , '..."
1,398454096642776,2 to 12 years,['bca'],56-116k,ashgabat,turkmenistan,intern,100340,2022-12-19,['female'],francisco larsen,"['web', 'developer']","['frontend', 'web', 'developer']",['idealist'],"[ 'frontend ' , 'web ' , 'developers ' , 'desi...","[ 'health ' , 'insurance ' , 'retirement ' , '...","['html', 'css', 'javascript', 'frontend', 'fra...","[ 'design ' , 'and ' , 'code ' , 'user ' , 'in...","['pnc', 'financial', 'services', 'group']","[ 'sector ' , 'financial ' , 'services ' , 'in..."
2,481640072963533,0 to 12 years,['phd'],61-104k,macao,macao sar china,temporary,84525,2022-09-14,['male'],gary gibson,"['operations', 'manager']","['quality', 'control', 'manager']",['jobs2careers'],"[ 'quality ' , 'control ' , 'managers ' , 'est...","[ 'legal ' , 'assistance ' , 'bonuses ' , 'and...","['quality', 'control', 'processes', 'and', 'me...","[ 'establish ' , 'and ' , 'enforce ' , 'qualit...","['united', 'services', 'automobile', 'assn']","[ 'sector ' , 'insurance ' , 'industry ' , 'in..."
3,688192671473044,4 to 11 years,['phd'],65-91k,portonovo,benin,fulltime,129896,2023-02-25,['female'],joy lucero,"['network', 'engineer']","['wireless', 'network', 'engineer']",['flexjobs'],"[ 'wireless ' , 'network ' , 'engineers ' , 'd...","[ 'transportation ' , 'benefits ' , 'professio...","['wireless', 'network', 'design', 'and', 'arch...","[ 'design ' , 'configure ' , 'and ' , 'optimiz...",['hess'],"[ 'sector ' , 'energy ' , 'industry ' , 'minin..."
4,117057806156508,1 to 12 years,['mba'],64-87k,santiago,chile,intern,53944,2022-10-11,['female'],julie johnson,"['event', 'manager']","['conference', 'manager']",['jobs2careers'],"[ ' ' , 'conference ' , 'manager ' , 'coordina...","[ 'flexible ' , 'spending ' , 'accounts ' , 'f...","['event', 'planning', 'conference', 'logistics...","[ 'specialize ' , 'in ' , 'conference ' , 'and...","['cairn', 'energy']","[ 'sector ' , 'energy ' , 'industry ' , 'energ..."

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

responsibilities_column = clean_data['Responsibilities']

# initialize the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# fit and transform the data
X_tfidf = tfidf_vectorizer.fit_transform(responsibilities_column)

In [3]:
# Assuming 'Skills' is the column containing skills information
skills_column = clean_data['skills']

# Initialize the TF-IDF vectorizer
tfidf_vectorizer_skills = TfidfVectorizer()

# Fit and transform the text data
X_tfidf_skills = tfidf_vectorizer_skills.fit_transform(skills_column)

# X_tfidf_skills is now a sparse matrix containing TF-IDF vectors for skills

In [4]:
# Assuming 'Job Title' is the column containing job titles
job_title_column = clean_data['Job Title']

# Initialize the TF-IDF vectorizer
tfidf_vectorizer_job_title = TfidfVectorizer()

# Fit and transform the text data
X_tfidf_job_title = tfidf_vectorizer_job_title.fit_transform(job_title_column)

# X_tfidf_job_title is now a sparse matrix containing TF-IDF vectors for job titles

In [5]:
# Assuming 'Qualifications' is the column containing qualifications information
qualifications_column = clean_data['Qualifications']

# Initialize the TF-IDF vectorizer
tfidf_vectorizer_qualifications = TfidfVectorizer()

# Fit and transform the text data
X_tfidf_qualifications = tfidf_vectorizer_qualifications.fit_transform(qualifications_column)

# X_tfidf_qualifications is now a sparse matrix containing TF-IDF vectors for qualifications

In [ ]:
# Convert sparse matrices to dense NumPy arrays
X_tfidf_dense = X_tfidf.toarray()

:

In [ ]:
X_tfidf_skills_dense = X_tfidf_skills.toarray()

In [ ]:

X_tfidf_job_title_dense = X_tfidf_job_title.toarray()

In [ ]:

X_tfidf_qualifications_dense = X_tfidf_qualifications.toarray()

In [2]:
# Assuming you have TF-IDF matrices for 'Responsibilities', 'Skills', 'Job Title', and 'Qualifications'

# Convert sparse matrices to dense NumPy arrays for better inspection
X_tfidf_dense = X_tfidf.toarray()
X_tfidf_skills_dense = X_tfidf_skills.toarray()
X_tfidf_job_title_dense = X_tfidf_job_title.toarray()
X_tfidf_qualifications_dense = X_tfidf_qualifications.toarray()

# Now you can print the dense matrices
print("TF-IDF Matrix for Responsibilities:")
print(X_tfidf_dense)

print("\nTF-IDF Matrix for Skills:")
print(X_tfidf_skills_dense)


print("\nTF-IDF Matrix for Job Title:")
print(X_tfidf_job_title_dense)

print("\nTF-IDF Matrix for Qualifications:")
print(X_tfidf_qualifications_dense)

NameError: name 'X_tfidf' is not defined

In [27]:
import pandas as pd

# Get feature names from the TF-IDF vectorizer
feature_names_responsibilities = tfidf_vectorizer.get_feature_names_out()
feature_names_skills = tfidf_vectorizer_skills.get_feature_names_out()
feature_names_job_title = tfidf_vectorizer_job_title.get_feature_names_out()
feature_names_qualifications = tfidf_vectorizer_qualifications.get_feature_names_out()

# Convert TF-IDF matrices to DataFrames
df_tfidf_responsibilities = pd.DataFrame(X_tfidf.toarray(), columns=feature_names_responsibilities)
df_tfidf_skills = pd.DataFrame(X_tfidf_skills_dense, columns=feature_names_skills)
df_tfidf_job_title = pd.DataFrame(X_tfidf_job_title_dense, columns=feature_names_job_title)
df_tfidf_qualifications = pd.DataFrame(X_tfidf_qualifications_dense, columns=feature_names_qualifications)

# Display DataFrames
print("TF-IDF DataFrame for Responsibilities:")
print(df_tfidf_responsibilities)

print("\nTF-IDF DataFrame for Skills:")
print(df_tfidf_skills)

print("\nTF-IDF DataFrame for Job Title:")
print(df_tfidf_job_title)

print("\nTF-IDF DataFrame for Qualifications:")
print(df_tfidf_qualifications)

: